export const DESTS = [
  {
    c:'UAE', slug:'uae', urlSlug:'dubai', f:'🇦🇪', type:'evisa', region:'middle-east',
    val:'30 days', docs:'3 docs', proc:'24 hrs', price:'₹999',
    img:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=90&fit=crop&auto=format',
    fullName:'United Arab Emirates', capital:'Abu Dhabi', currency:'AED (Dirham)', language:'Arabic',
    successRate:'99%',
    about:'The UAE e-Visa lets you explore the dazzling cities of Dubai and Abu Dhabi. Issued entirely online, it is delivered to your email within 24 hours. Perfect for tourism, business, and transit.',
    requirements:['Valid Indian passport (min. 6 months validity)','Recent passport-size photo (white background)','Confirmed return air ticket','Hotel booking or host invitation letter','Last 3 months bank statement (min. ₹1 lakh balance)','Travel insurance covering UAE'],
    includes:['Professional application review','e-Visa delivery to email','Real-time WhatsApp updates','Re-apply free if rejected (Pro plan)','GST invoice for business travel'],
    contentSections:[
      { h2:'Do Indians Need a Visa for Dubai?', body:'Yes — Indian passport holders require a visa to enter the UAE, including Dubai and Abu Dhabi. However, the UAE e-Visa is one of the easiest and fastest to obtain in the world. It\'s applied for entirely online, processed in 24–48 hours, and delivered to your email — no embassy visit, no biometrics, no interview. There is one exception: Indians who hold a valid, unexpired visa for the USA, UK, EU Schengen area, or certain other countries may be eligible for a visa on arrival at UAE airports. This is not automatic — it depends on the specific type of visa you hold (tourist, business, or resident visas typically qualify; some others don\'t). If you\'re unsure whether your existing visa qualifies for UAE visa on arrival, contact us on WhatsApp for a quick check before your travel.' },
      { h2:'Types of Dubai Visas for Indians — 14, 30, or 60 Days?', body:'The UAE offers multiple tourist visa durations for Indians. The 14-day single-entry visa suits quick trips and short business visits. The 30-day single-entry visa is the most popular for holidays — enough time for Dubai, Abu Dhabi, Sharjah, and a day trip to Oman if you like. The 60-day visa is ideal for extended stays, visiting family, or combining work and leisure over a longer period. Multiple-entry visas are also available for frequent travellers — valid for 90 days with multiple entries, each allowing up to 30 days inside the UAE. For first-time visitors planning a standard Dubai holiday, the 30-day visa hits the right balance of cost and flexibility. Our team advises on the right type based on your specific itinerary and travel history.' },
      { h2:'Dubai Visa Price for Indians in Rupees — The Real Numbers', body:'Dubai visa pricing varies by duration and type. As a general guide: 14-day single-entry e-Visa costs approximately ₹3,500–5,000 in total (UAE government fee + service charge). 30-day single-entry runs ₹5,500–8,000. 60-day visa runs ₹9,000–12,000. These are approximate totals that include the UAE government processing fee and service charges. Prices you see advertised below ₹1,999 for a 30-day visa should be treated with skepticism — Dubai Police have flagged a sharp rise in visa scams where applicants pay, receive a fake visa PDF, and only discover the fraud at the UAE airport. The eVisa must be issued by the General Directorate of Residency and Foreigners Affairs (GDRFA) or verified UAE airlines. We provide the official source document with your application confirmation for verification.' },
      { h2:'Dubai Visa Overstay Fine — What Happens If You Stay Even One Day Too Long', body:'This is the single most important thing to know before travelling to Dubai: the UAE has zero tolerance for overstay, and the fines are automatic. As of 2025, the overstay fine is AED 50 per day (approximately ₹1,150/day) for the first six months, escalating to AED 500 per day (approximately ₹11,500/day) after six months. There is no grace period — day 31 of a 30-day visa is an overstay. If you overstay for more than 6 months, you also face a re-entry ban. If you have outstanding fines, you cannot leave UAE until they are settled — which means you may miss your flight home. The solution is straightforward: plan your departure before your visa expires, and if your plans change, apply for a visa extension inside the UAE before expiry, not after.' },
      { h2:'Dubai Visa Scams — How to Spot and Avoid Fake Agents', body:'UAE visa fraud targeting Indians has increased significantly. The most common pattern: a WhatsApp number advertising Dubai visa at ₹1,500–2,000, requests advance payment via UPI, sends a professional-looking PDF "visa", and disappears. The fake visa looks authentic but fails the GDRFA verification check at the airport. You are denied boarding, lose your flight, and have no recourse. Red flags to watch for: prices significantly below market rate, agents who only communicate via personal WhatsApp (not a business account), no GST invoice offered, no official website with business registration details, and requests for payment to a personal UPI ID rather than a company account. eVisas.in provides a GST invoice for every transaction, a GDRFA-verifiable visa document, and a business-registered WhatsApp number. When in doubt, verify your visa at the official GDRFA website before your travel date.' },
      { h2:'Can You Extend a Dubai Tourist Visa Inside UAE?', body:'Yes — tourist visa extensions are possible inside the UAE without leaving. You can apply through an ICA-approved typing centre or online through GDRFA Dubai\'s website. A standard 30-day extension costs AED 600 (approx. ₹14,000) plus a small service fee. You must apply before your current visa expires — applying even one day late incurs the overstay fine in addition to extension fees. Extensions can be done up to twice on most tourist visa types. A popular alternative is an "exit and re-enter" — flying to Oman, Georgia, or another short-hop destination for a day and re-entering UAE on a new visa. This works but is not always guaranteed, as immigration officers may question repeated UAE visits on tourist visas.' },
    ],
    faqs:[
      { q:'Can Indians get Dubai visa on arrival in 2025?', a:'Indians without a qualifying foreign visa must apply for a UAE e-Visa before travel. However, Indians who hold a valid US, UK, EU Schengen, or certain other country visas may be eligible for UAE visa on arrival at the airport. The qualifying visa must be valid for at least 6 months. If you\'re unsure whether your existing visa qualifies, message us on WhatsApp for a quick check before you book flights.' },
      { q:'What is the Dubai tourist visa price in rupees for 30 days?', a:'A 30-day UAE tourist e-Visa costs approximately ₹5,500–8,000 total (government fee + processing). Be cautious of prices significantly below this range — Dubai Police have reported a rise in visa fraud cases where fake visa PDFs are sold at unusually low prices and fail verification at the airport.' },
      { q:'How long does Dubai visa processing take from India?', a:'Standard UAE e-Visa processing from India takes 24–48 hours. In most cases, approvals arrive within a few hours of submission during working hours. Express processing (for urgent travel) can sometimes be done in 4–6 hours through priority channels. We recommend applying at least 3–4 days before travel to have a buffer.' },
      { q:'What happens if I overstay my Dubai visa by even one day?', a:'The UAE charges AED 50 per day (approximately ₹1,150) for overstay, starting from day one after visa expiry. There is no grace period. Outstanding fines must be paid before you can exit the UAE. Overstaying more than 6 months results in a re-entry ban. If your plans change and you need to extend your stay, apply for a visa extension through GDRFA before your current visa expires.' },
      { q:'Can I work on a Dubai tourist visa?', a:'No — working on a tourist visa in the UAE is illegal and can result in immediate deportation, a re-entry ban, and fines for both you and any employer. If you are travelling to Dubai for job interviews or business meetings (not employment), this is generally permitted on a tourist visa. Actual employment requires a work permit and residence visa sponsored by your employer.' },
      { q:'Can I extend my Dubai tourist visa while inside the UAE?', a:'Yes. Tourist visa extensions can be applied for through GDRFA Dubai or an ICA-approved typing centre. A standard extension costs AED 600 (approx. ₹14,000). You must apply before your current visa expiry — post-expiry extension is not possible, and overstay fines apply. Most tourist visas can be extended twice.' },
    ],
  },
  {
    c:'Thailand', slug:'thailand', urlSlug:'thailand', f:'🇹🇭', type:'voa', region:'asia',
    val:'30 days', docs:'2 docs', proc:'On arrival', price:'₹499',
    img:'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=90&fit=crop&auto=format',
    fullName:'Thailand', capital:'Bangkok', currency:'THB (Baht)', language:'Thai',
    successRate:'98%',
    about:'Indians can get a Visa on Arrival at major Thai airports. We prepare all your documents in advance so you sail through the VOA counter in minutes — no stress, no confusion.',
    requirements:['Valid Indian passport (min. 6 months validity)','Recent passport-size photo','Proof of onward travel','Cash for VOA fee (2,000 THB ≈ ₹4,800)','Hotel booking confirmation','Sufficient funds proof (THB 10,000 per person)'],
    includes:['VOA document preparation kit','Step-by-step airport guide','Completed arrival card','Pre-filled VOA form','24/7 WhatsApp support during travel'],
  },
  {
    c:'France', slug:'france', urlSlug:'schengen', f:'🇫🇷', type:'sticker', region:'europe',
    val:'90 days', docs:'8 docs', proc:'15 days', price:'₹1,999',
    img:'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&q=90&fit=crop&auto=format',
    fullName:'France (Schengen)', capital:'Paris', currency:'EUR (Euro)', language:'French',
    successRate:'96%',
    about:'A France Schengen visa allows travel across 27 European countries. Our experts handle your entire application — from document compilation to appointment scheduling — giving you the best chance of approval.',
    requirements:['Valid Indian passport (min. 3 months beyond return date)','Two recent passport photos (Schengen specs)','Confirmed return air ticket','Proof of accommodation for entire stay','Travel insurance (min. €30,000 cover)','Last 3 months bank statements','ITR / salary slips (last 3 months)','Employment letter / leave approval'],
    includes:['Expert document review & checklist','Visa appointment scheduling','Application form filling','Embassy submission support','Rejection analysis if needed (Pro plan)'],
  },
  {
    c:'USA', slug:'usa', urlSlug:'usa', f:'🇺🇸', type:'sticker', region:'americas',
    val:'10 years', docs:'6 docs', proc:'30 days', price:'₹4,999',
    img:'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=1200&q=90&fit=crop&auto=format',
    fullName:'United States of America', capital:'Washington D.C.', currency:'USD (Dollar)', language:'English',
    successRate:'87%',
    about:'The US B1/B2 tourist & business visa is valid for 10 years with multiple entries. Our mock interview tool and expert coaching dramatically improve your approval odds — our clients have an 87% success rate vs 68% national average.',
    requirements:['Valid Indian passport (min. 6 months validity)','DS-160 form (completed online)','Visa fee payment confirmation (MRV receipt)','Appointment confirmation letter','Photo per US specifications','Income proof (ITR, Form 16, bank statements)','Property / asset documents (as applicable)'],
    includes:['DS-160 form filling','Mock interview practice (50+ questions)','Document checklist & review','Appointment scheduling at nearest consulate','Pre-interview preparation call','Post-interview guidance'],
    contentSections:[
      { h2:'Do Indians Need a Visa for the USA?', body:'Yes — Indian passport holders require a B1/B2 non-immigrant visa for tourism, family visits, and business trips to the United States. There is no visa-on-arrival facility for Indians. The B1/B2 visa, once granted, is valid for 10 years with unlimited entries, making it one of the most valuable travel documents an Indian passport can hold. You can stay up to 6 months per visit. The application involves a DS-160 form, visa fee payment, biometrics, and a mandatory in-person interview at a US consulate in India.' },
      { h2:'The 3-Minute Interview That Decides Everything', body:'The US visa interview is unlike anything else in the visa world. A consular officer has roughly 2–4 minutes to decide whether you deserve a 10-year visa. In that window, they\'re looking for one thing: confidence that you will return to India. What trips people up isn\'t lying — it\'s the way honest answers can sound suspicious when unprepared. Saying "my son is in the US" without immediately following up with "and I have my business, property, and elderly parents in India" is exactly the kind of incomplete answer that leads to rejection. Our interview prep covers 50+ real questions asked at Delhi, Mumbai, Chennai, and Hyderabad consulates — including the uncomfortable ones about family abroad and travel history.' },
      { h2:'Understanding 214(b) — The Most Common Rejection Reason', body:'Section 214(b) of the US Immigration and Nationality Act presumes every applicant is an intending immigrant. The burden is entirely on you to prove otherwise. A 214(b) refusal doesn\'t mean you were dishonest — it means the officer wasn\'t convinced you have strong enough ties to India to return. Common triggers include: being young and unmarried, having no property in your name, low bank balance relative to your stated travel purpose, or a parent/sibling on a US visa/green card. The good news: a 214(b) refusal has no mandatory waiting period. You can reapply immediately — but only if you address the exact weaknesses the officer saw. Reapplying with the same documents and hoping for a different officer is the most expensive mistake you can make.' },
      { h2:'How to Prove Strong Ties to India — The Right Way', body:'Strong ties is a phrase that confuses many applicants. Officers aren\'t looking for a house deed — they\'re looking for a believable life in India that you\'d have strong reasons to return to. Property ownership helps but isn\'t mandatory. What matters more is a combination of: stable employment with a leave letter from your employer, dependent family members (spouse, children, parents who rely on you), financial commitments (home loan, business responsibilities), and a travel history that shows you\'ve returned from previous trips. If you\'re self-employed, your business existence — GST registration, client invoices, shop photos — becomes your strongest tie. We help you identify which ties in your specific situation are worth emphasising, and which documents prove them most convincingly.' },
      { h2:'US Visa Appointment Wait Times Across India in 2025', body:'Appointment availability is currently one of the most frustrating parts of the US visa process. As of 2025, wait times vary dramatically by city. Delhi and Mumbai typically show 3–6 month waits for first-time applicants. Chennai, Hyderabad, and Kolkata occasionally have shorter windows but fill up within hours of opening. The Emergency Appointment system exists for genuine urgent cases but is tightly controlled. One workaround: reschedule alerts. Slots open up daily as people cancel. Checking early morning (around 6–7 AM) significantly improves your chances. We monitor slot availability for our clients and notify you the moment a closer slot opens at any of the five consulates.' },
      { h2:'US Visa Fees for Indians in 2025 (Full Breakdown in ₹)', body:'The US visa fee structure changed in 2025. The standard MRV (Machine Readable Visa) fee is $185 (approx. ₹15,500), paid before the appointment. From October 2025, a $250 Visa Integrity Fee (approx. ₹20,900) applies to most B1/B2 applicants. Total government fees alone: approximately ₹36,400. This does not include our service fee of ₹4,999, which covers DS-160 preparation, interview coaching, document review, and appointment support. The MRV fee is non-refundable even if the visa is refused — which is exactly why preparation matters so much. We help ensure you only pay these fees once.' },
      { h2:'US Visa Documents Checklist for Indians', body:'Beyond the standard passport and photo, what separates approved applications is the quality of financial and personal documentation. Your bank statements should show consistent, organic balances — not a sudden deposit right before applying. Income documents (ITR, Form 16, salary slips) should match your stated employment. Property documents add significant weight for self-employed applicants. If you have family in the US, prepare a sponsor letter from them and be ready to clearly articulate that your relationship with them is the reason for the visit — not a reason you won\'t return. Travel history to other countries (especially if you\'ve returned on time from each) is one of the strongest assets you can have.' },
    ],
    faqs:[
      { q:'Can I get US visa if my son or daughter is on H1-B in the USA?', a:'Yes — Indians with close family on H1-B or Green Card are approved for US visitor visas regularly. The key is to proactively address the "pull factor" concern during your interview. Clearly state your ties to India: your business or employment, property, and any dependents who rely on you. Frame the visit as a family vacation with a clear return plan, not an open-ended trip. Officers will scrutinize this more carefully, but a well-prepared application absolutely succeeds.' },
      { q:'What is 214(b) refusal and can I reapply immediately?', a:'214(b) means the officer was not convinced you intend to return to India after your visit. There is no mandatory waiting period — you can reapply as soon as the next day. However, reapplying without addressing the specific reasons for refusal almost always leads to the same outcome. Identify what was weak (income level, family ties, travel history) and strengthen those areas with better documentation before your next attempt.' },
      { q:'How long does it take to get US visa from India?', a:'Once you have an appointment, the visa is typically issued within 3–5 working days after your interview if approved. The bottleneck is getting the appointment itself — current wait times range from 3 to 9 months depending on the consulate city and time of year. Planning 6 months ahead is advisable for non-urgent travel.' },
      { q:'What questions are asked in US visa interview for Indians?', a:'Common questions include: Why do you want to visit the US? Who is funding your trip? Do you have family in the US? What do you do for work? Have you ever been refused a US visa? Do you own property in India? What are your plans after returning? The goal is always to establish that you have a life in India worth returning to. The best answers are specific and honest — vague or rehearsed-sounding responses raise flags.' },
      { q:'How much bank balance is needed for US tourist visa from India?', a:'There is no officially stated minimum, but as a general guideline, a balance that comfortably covers your stated travel expenses (flights, hotel, daily costs for the duration of your trip) — typically ₹5–10 lakh for a 2–3 week trip — is considered adequate. More importantly, the balance should reflect organic saving patterns, not a sudden influx of funds. Statements showing steady deposits over 6 months are significantly more convincing than a high balance with one large recent transfer.' },
      { q:'Can I apply for US visa on my own or do I need an agent?', a:'You can apply independently — the DS-160 form and fee payment are done online without a mandatory agent. However, the interview preparation, document strategy, and understanding of what officers are looking for is where most rejections happen. Our service specifically focuses on the human element of the US visa — preparing you for the interview and helping structure your documents in the way that most clearly communicates your strong ties to India.' },
    ],
  },
  {
    c:'Singapore', slug:'singapore', urlSlug:'singapore', f:'🇸🇬', type:'evisa', region:'asia',
    val:'30 days', docs:'3 docs', proc:'3 days', price:'₹999',
    img:'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200&q=90&fit=crop&auto=format',
    fullName:'Singapore', capital:'Singapore City', currency:'SGD (Dollar)', language:'English',
    successRate:'97%',
    about:'Singapore\'s e-Visa (EPAS) is issued online and linked to your passport electronically — no sticker, no stamp needed until arrival. Processed in 3 business days, perfect for short Asia getaways.',
    requirements:['Valid Indian passport (min. 6 months validity)','Digital passport photo','Confirmed return air ticket','Hotel booking confirmation','Last 3 months bank statement'],
    includes:['e-Visa application submission','Document quality check','Electronic approval notification','WhatsApp status updates','24/7 expert support'],
    contentSections:[
      { h2:'Singapore Visa on Arrival for Indians — The Myth, Busted', body:'This is the most common misconception about Singapore travel: Indians cannot get a visa on arrival. Singapore has no visa-on-arrival programme for Indian passport holders. What exists is the Visa-Free Transit Facility (VFTF), which allows eligible passengers to transit Singapore airport for up to 96 hours without a visa — but only if you hold a valid visa for the US, UK, Canada, Australia, or certain other countries, and you\'re transiting to a third destination. If you\'re travelling to Singapore as your final destination, you need a pre-approved visa — no exceptions. There is one real shortcut: if you hold a valid, unexpired US visa, UK visa, or other qualifying document, you may be eligible for the VFTF on your way through Changi. But for a Singapore holiday, e-Visa is the only path for Indians.' },
      { h2:'Why Singapore Visa Must Be Done Through an Authorized Agent', body:'The Immigration & Checkpoints Authority (ICA) of Singapore does not accept direct applications from Indian nationals. All Singapore visa applications from India must be submitted through an authorized visa agent — this is not optional, and it\'s not bureaucratic friction. It\'s Singapore\'s quality control mechanism. The ICA expects the agent to have verified the documents before submission, which means the agent is essentially co-signing the application. This is why document accuracy matters so much: if your photo dimensions are off by 1mm, if your bank statement is older than 3 months, or if your return ticket shows the wrong dates, the agent will flag it before submission — or worse, submit anyway and get it rejected. We are an authorized Singapore visa agent, and our document quality check catches errors before they cost you a visa.' },
      { h2:'Singapore Visa Documents — Where Most Applications Go Wrong', body:'Singapore\'s requirements look simple on paper: passport, photo, ticket, hotel, bank statement. The devil is in the specifications. The digital photo must be exactly 400×514 pixels, taken within the last 3 months, with a white background, 80% face coverage, and no glasses. Bank statements must not be older than 3 months from the date of application — printing a 4-month-old statement is an immediate flag. Your hotel booking must cover every single night of your intended stay — a gap of even one night creates questions. The return flight must be booked (not just searched) before you apply. None of these individually is complicated. But together, getting all five elements exactly right on the first submission is where most self-attempts fail and most rejections originate.' },
      { h2:'Singapore Visa Fee for Indians — Full Cost Breakdown', body:'The Singapore visa fee charged by ICA is SGD 30 (approximately ₹1,900 at current rates). This is paid per application, whether approved or rejected, so it\'s non-refundable. Our service fee of ₹999 covers the authorized agent submission, document quality review, and WhatsApp tracking throughout processing. Total cost for a Singapore visa from India: approximately ₹2,900 all-in. For context, most aggregator sites in India charge ₹2,500–5,000 for the same process without the quality review step. Singapore visa is genuinely affordable — the risk is not cost, it\'s document error.' },
      { h2:'The 30-Day Application Window — When to Apply', body:'Singapore visa applications must be submitted no more than 30 days before your intended arrival date. Applying earlier than 30 days will result in rejection. Applying less than 3 working days before travel is cutting it too close — processing takes 3–5 working days and there\'s no guaranteed rush option for tourist visas. The sweet spot: apply 7–14 days before your travel date. This gives you time to receive the approval, print it, and have a buffer for reapplication if something goes wrong. Once approved, your visa is typically valid for 30 days from the date of approval — not from your travel date — so don\'t apply too early either.' },
      { h2:'Singapore Visa With a Previous Rejection — What to Know', body:'A previous Singapore visa rejection does not permanently bar you from reapplying, but it does require honest disclosure. ICA\'s system tracks all previous applications and outcomes. Failing to mention a prior rejection on a new application is treated as misrepresentation and can result in a longer ban or permanent refusal. If you\'ve been rejected before, the key is identifying why. ICA doesn\'t explain rejections — which means you need to assess your own application objectively. Common reasons: insufficient bank balance (below SGD 1,500 equivalent for the trip duration), inconsistency between stated purpose and booking details, or a photo that didn\'t meet specifications. Address the actual issue, not just the symptom.' },
    ],
    faqs:[
      { q:'Is there Singapore visa on arrival for Indian passport holders in 2025?', a:'No. Indians cannot get visa on arrival in Singapore. You must obtain a pre-approved e-Visa before travel. The only exception is the VFTF (Visa-Free Transit Facility) for passengers transiting through Singapore with a valid US, UK, Australian, or Canadian visa — but this applies only to airport transits, not travel to Singapore itself.' },
      { q:'Can I apply for Singapore visa directly or do I need an agent?', a:'Indian nationals cannot apply directly to ICA (Singapore\'s immigration authority). Applications from India must be submitted through an ICA-authorized visa agent. This is a mandatory requirement, not optional. eVisas.in is an authorized agent and handles the full submission process on your behalf.' },
      { q:'What is Singapore VFTF and who is eligible?', a:'The Visa-Free Transit Facility (VFTF) allows eligible passengers to transit through Singapore Changi Airport for up to 96 hours without a Singapore visa. You qualify if you hold a valid visa for the USA, UK, Canada, Australia, Germany, France, Japan, or other listed countries, and you\'re transiting to a third destination. VFTF is not a substitute for a tourist visa if Singapore is your final destination.' },
      { q:'How early should I apply for Singapore visa from India?', a:'Apply 7–14 days before your travel date. Singapore visa must be applied no more than 30 days before arrival — earlier applications will be rejected. Processing takes 3–5 working days in most cases. Applying 7 days out gives you processing time plus a small buffer for reapplication if needed.' },
      { q:'What happens if Singapore visa is rejected? Can I reapply?', a:'You can reapply after a rejection, but you must declare the previous rejection on the new application. Before reapplying, identify what likely caused the rejection — common reasons are photo specification errors, bank balance below the threshold, or incomplete hotel bookings. Addressing the actual issue (not just resubmitting the same documents) gives you the best chance of approval on the second attempt.' },
      { q:'Can Indians with a valid US or Schengen visa get Singapore visa on arrival?', a:'No — even with a US or Schengen visa, Indians cannot get Singapore visa on arrival for a tourist trip. However, Indians holding a valid US, UK, or Australian visa who are transiting through Changi Airport can use the VFTF (up to 96 hours, no Singapore visa needed). For travel to Singapore itself, a pre-approved visa is always required for Indian passport holders.' },
    ],
  },
  {
    c:'Maldives', slug:'maldives', urlSlug:'maldives', f:'🇲🇻', type:'voa', region:'asia',
    val:'30 days', docs:'1 doc', proc:'On arrival', price:'₹999',
    img:'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&q=90&fit=crop&auto=format',
    fullName:'Maldives', capital:'Malé', currency:'MVR (Rufiyaa)', language:'Dhivehi',
    successRate:'100%',
    about:'Indians receive a free 30-day Visa on Arrival in the Maldives — no pre-approval needed. We provide a document checklist and travel guide so you\'re fully prepared for your island getaway.',
    requirements:['Valid Indian passport (min. 6 months validity)','Confirmed return air ticket','Hotel/resort booking (mandatory)','Proof of sufficient funds'],
    includes:['Pre-travel document checklist','Arrival guide & customs tips','Hotel booking assistance','24/7 WhatsApp support'],
  },
  {
    c:'Turkey', slug:'turkey', urlSlug:'turkey', f:'🇹🇷', type:'evisa', region:'middle-east',
    val:'90 days', docs:'2 docs', proc:'24 hrs', price:'₹999',
    img:'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1200&q=90&fit=crop&auto=format',
    fullName:'Turkey', capital:'Ankara', currency:'TRY (Lira)', language:'Turkish',
    successRate:'98%',
    about:'Turkey\'s e-Visa grants a single or multiple entry visit valid for 90 days. It is issued within 24 hours and allows you to explore Istanbul, Cappadocia, the Turquoise Coast, and more.',
    requirements:['Valid Indian passport (min. 6 months validity)','Active email address','International debit/credit card (for embassy fee)','Return air ticket (may be requested)'],
    includes:['e-Visa application filing','Instant email delivery','WhatsApp updates','Re-apply support if any issues'],
  },
  {
    c:'UK', slug:'uk', urlSlug:'uk', f:'🇬🇧', type:'sticker', region:'europe',
    val:'6 months', docs:'7 docs', proc:'21 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&q=90&fit=crop&auto=format',
    fullName:'United Kingdom', capital:'London', currency:'GBP (Pound)', language:'English',
    successRate:'91%',
    about:'The UK Standard Visitor Visa allows Indians to visit for tourism, business, or family for up to 6 months. Our experts craft a strong application with a compelling cover letter that greatly increases approval odds.',
    requirements:['Valid Indian passport (min. 6 months validity)','Online application (UKVi portal)','Biometrics appointment at VFS','Bank statements (last 6 months)','Employment letter & leave approval','Property or asset evidence','Travel itinerary & hotel bookings','Sponsor letter (if applicable)'],
    includes:['UKVi form completion','Biometrics appointment booking','Cover letter drafting','Document compilation & review','VFS submission support','Approval tracking'],
  },
  {
    c:'Indonesia', slug:'indonesia', urlSlug:'bali', f:'🇮🇩', type:'voa', region:'asia',
    val:'30 days', docs:'2 docs', proc:'On arrival', price:'₹999',
    img:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=90&fit=crop&auto=format',
    fullName:'Indonesia', capital:'Jakarta', currency:'IDR (Rupiah)', language:'Bahasa Indonesia',
    successRate:'99%',
    about:'Indonesia\'s B211A visa-on-arrival covers Bali and other major gateways. Indians can also apply online via e-VOA before flying. We handle preparation and pre-fill all required documents.',
    requirements:['Valid Indian passport (min. 6 months validity)','Return air ticket','Hotel booking confirmation','Payment for VOA fee (USD 35)','Onward travel evidence'],
    includes:['e-VOA application (recommended)','Document kit preparation','Arrival & immigration guide','WhatsApp support in Bali hours'],
  },
  {
    c:'Germany', slug:'germany', urlSlug:'germany', f:'🇩🇪', type:'sticker', region:'europe',
    val:'90 days', docs:'8 docs', proc:'15 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&q=90&fit=crop&auto=format',
    fullName:'Germany (Schengen)', capital:'Berlin', currency:'EUR (Euro)', language:'German',
    successRate:'95%',
    about:'A Germany Schengen visa opens doors to 27 European countries. VFS appointments in India can be hard to get — we secure them for you while building a flawless application.',
    requirements:['Valid Indian passport (min. 3 months beyond return date)','Two Schengen-spec photos','Confirmed flights & accommodation','Travel insurance (€30,000 minimum)','Last 3 months bank statements','Salary slips & ITR','Employment confirmation letter','Leave sanction letter'],
    includes:['VFS appointment booking','Complete document compilation','Application form filling','Expert review & checklist','Embassy submission coordination'],
  },
  {
    c:'Malaysia', slug:'malaysia', urlSlug:'malaysia', f:'🇲🇾', type:'evisa', region:'asia',
    val:'30 days', docs:'3 docs', proc:'3 days', price:'₹1,999',
    img:'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1200&q=90&fit=crop&auto=format',
    fullName:'Malaysia', capital:'Kuala Lumpur', currency:'MYR (Ringgit)', language:'Bahasa Malaysia',
    successRate:'97%',
    about:'Malaysia\'s eNTRI and e-Visa are fully online. Most Indians qualify for eNTRI (free, 15 days). We help you choose the right visa type and ensure your application is error-free.',
    requirements:['Valid Indian passport (min. 6 months validity)','Digital passport photo','Return air ticket','Hotel booking or host letter','Onward travel proof'],
    includes:['Visa type selection (eNTRI or eVisa)','Application submission','Document review','WhatsApp updates','Airport arrival tips'],
  },
  {
    c:'Kenya', slug:'kenya', urlSlug:'kenya', f:'🇰🇪', type:'evisa', region:'africa',
    val:'90 days', docs:'3 docs', proc:'3 days', price:'₹1,999',
    img:'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&q=90&fit=crop&auto=format',
    fullName:'Kenya', capital:'Nairobi', currency:'KES (Shilling)', language:'Swahili & English',
    successRate:'97%',
    about:'Kenya\'s eCitizen e-Visa is perfect for Indian safari lovers and nature enthusiasts. Valid for 90 days, it covers single entry to Nairobi, Mombasa, Masai Mara, and beyond.',
    requirements:['Valid Indian passport (min. 6 months validity)','Digital passport photo','Return air ticket','Yellow fever vaccination certificate','Hotel or safari lodge booking','Bank statement (last 3 months)'],
    includes:['eCitizen application filing','Vaccination guidance','Safari booking tips','WhatsApp status updates','e-Visa email delivery'],
  },
  {
    c:'Japan', slug:'japan', urlSlug:'japan', f:'🇯🇵', type:'sticker', region:'asia',
    val:'15 days', docs:'6 docs', proc:'5 days', price:'₹1,999',
    img:'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=90&fit=crop&auto=format',
    fullName:'Japan', capital:'Tokyo', currency:'JPY (Yen)', language:'Japanese',
    successRate:'93%',
    about:'Japan tourist visa for Indians requires a sticker visa from the Japanese consulate. Our experts compile every document to maximize approval chances for this dream destination.',
    requirements:['Valid passport (min 6 months validity)','Recent photo (45×45mm, white bg)','Confirmed flight & hotel bookings','Bank statement (min ₹2 lakh)','ITR / salary slips (3 months)','Employment letter & leave approval'],
    includes:['Complete document compilation','Application form filling','Consulate submission','Day-by-day itinerary creation','WhatsApp tracking'],
  },
  {
    c:'Vietnam', slug:'vietnam', urlSlug:'vietnam', f:'🇻🇳', type:'evisa', region:'asia',
    val:'90 days', docs:'2 docs', proc:'3 days', price:'₹999',
    img:'https://images.unsplash.com/photo-1557456170-0cf4f4d0d362?w=1200&q=90&fit=crop&auto=format',
    fullName:'Vietnam', capital:'Hanoi', currency:'VND (Dong)', language:'Vietnamese',
    successRate:'98%',
    about:'Vietnam e-Visa allows Indians to explore Ha Long Bay, Hoi An, and Ho Chi Minh City. Issued fully online and valid for 90 days with multiple entries.',
    requirements:['Valid passport (min 6 months validity)','Passport-size digital photo','Return flight confirmation','Hotel booking or itinerary'],
    includes:['e-Visa application filing','Document quality check','Email delivery of visa','WhatsApp status updates'],
  },
  {
    c:'Sri Lanka', slug:'srilanka', urlSlug:'sri-lanka', f:'🇱🇰', type:'evisa', region:'asia',
    val:'30 days', docs:'3 docs', proc:'48 hrs', price:'₹499',
    img:'https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=1200&q=90&fit=crop&auto=format',
    fullName:'Sri Lanka', capital:'Colombo', currency:'LKR (Rupee)', language:'Sinhala',
    successRate:'99%',
    about:'Sri Lanka ETA (Electronic Travel Authorization) is issued online for Indian tourists. Explore beaches, temples, and tea plantations with this easy online visa.',
    requirements:['Valid passport (min 6 months validity)','Passport-size digital photo','Return flight confirmation','Hotel or host letter'],
    includes:['ETA application filing','Document review','Email delivery','24/7 WhatsApp support'],
  },
  {
    c:'Cambodia', slug:'cambodia', urlSlug:'cambodia', f:'🇰🇭', type:'evisa', region:'asia',
    val:'30 days', docs:'2 docs', proc:'3 days', price:'₹999',
    img:'https://images.unsplash.com/photo-1555652736-e92021d28a10?w=1200&q=90&fit=crop&auto=format',
    fullName:'Cambodia', capital:'Phnom Penh', currency:'KHR (Riel)', language:'Khmer',
    successRate:'99%',
    about:'Cambodia e-Visa is perfect for visiting Angkor Wat and the temples of Siem Reap. Issued online, delivered to your email, and accepted at all major entry points.',
    requirements:['Valid passport (min 6 months validity)','Digital passport photo (4×6cm, white bg)','Return air ticket'],
    includes:['e-Visa application filing','Photo quality check','Email delivery','Entry tips for Siem Reap'],
  },
  {
    c:'Azerbaijan', slug:'azerbaijan', urlSlug:'azerbaijan', f:'🇦🇿', type:'evisa', region:'asia',
    val:'30 days', docs:'2 docs', proc:'3 days', price:'₹799',
    img:'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=90&fit=crop&auto=format',
    fullName:'Azerbaijan', capital:'Baku', currency:'AZN (Manat)', language:'Azerbaijani',
    successRate:'97%',
    about:"Azerbaijan's ASAN e-Visa is one of the easiest to get — just 2 documents and 3 days processing. Explore the futuristic flame towers of Baku, ancient cave cities, and the Caspian coastline. Highly affordable, visa-friendly for Indians.",
    requirements:['Valid Indian passport (min. 3 months validity beyond travel dates)','Recent passport-size photo','Travel itinerary / flight booking','Hotel booking confirmation'],
    includes:['ASAN e-Visa application filing','e-Visa delivery to email','Real-time WhatsApp updates','Re-apply free if rejected (Pro plan)','GST invoice'],
  },
  {
    c:'South Korea', slug:'southkorea', urlSlug:'south-korea', f:'🇰🇷', type:'sticker', region:'asia',
    val:'30 days', docs:'5 docs', proc:'7 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1617369120004-4fc70312c5e6?w=1200&q=90&fit=crop&auto=format',
    fullName:'South Korea', capital:'Seoul', currency:'KRW (Won)', language:'Korean',
    successRate:'91%',
    about:'South Korea tourist visa (C-3) lets you explore Seoul, Jeju Island, and the K-culture scene. Indians with a valid US, UK, or Schengen visa may enter visa-free — we check your eligibility first.',
    requirements:['Valid passport (min 6 months validity)','Passport photo (3.5×4.5cm, white bg)','Bank statement (min ₹1.5 lakh)','Return flight & hotel booking','Employment letter / business proof','ITR for last 2 years'],
    includes:['Eligibility check (visa-free assessment)','Application form filling','Document compilation','Consulate submission coordination','WhatsApp tracking'],
  },
  {
    c:'Italy', slug:'italy', urlSlug:'italy', f:'🇮🇹', type:'sticker', region:'europe',
    val:'90 days', docs:'8 docs', proc:'15 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&q=90&fit=crop&auto=format',
    fullName:'Italy (Schengen)', capital:'Rome', currency:'EUR (Euro)', language:'Italian',
    successRate:'94%',
    about:'An Italy Schengen visa lets you travel across all 27 Schengen countries. Our experts handle every document and can secure fast VFS appointments, giving you the best chance of approval.',
    requirements:['Valid passport (min 3 months beyond return date)','Two recent Schengen-spec photos','Confirmed return flight & accommodation','Travel insurance (min €30,000 cover)','Last 3 months bank statements','Salary slips & ITR','Employment / leave letter'],
    includes:['VFS appointment booking','Complete document compilation','Application form filling','Expert review','Embassy submission support'],
  },
  {
    c:'Spain', slug:'spain', urlSlug:'spain', f:'🇪🇸', type:'sticker', region:'europe',
    val:'90 days', docs:'8 docs', proc:'15 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1200&q=90&fit=crop&auto=format',
    fullName:'Spain (Schengen)', capital:'Madrid', currency:'EUR (Euro)', language:'Spanish',
    successRate:'93%',
    about:'Spain Schengen visa opens up all of Europe. From Barcelona\'s architecture to Madrid\'s museums, our experts craft a strong application to get you there.',
    requirements:['Valid passport (min 3 months beyond return date)','Two Schengen-spec photos','Return flight & hotel confirmations','Travel insurance (€30,000 minimum)','Bank statements (3 months)','ITR & salary slips','Leave sanction letter'],
    includes:['VFS appointment scheduling','Document compilation & review','Application form filling','Cover letter drafting','WhatsApp status updates'],
  },
  {
    c:'Netherlands', slug:'netherlands', urlSlug:'netherlands', f:'🇳🇱', type:'sticker', region:'europe',
    val:'90 days', docs:'8 docs', proc:'15 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=1200&q=90&fit=crop&auto=format',
    fullName:'Netherlands (Schengen)', capital:'Amsterdam', currency:'EUR (Euro)', language:'Dutch',
    successRate:'95%',
    about:'Netherlands Schengen visa for Indians. Amsterdam, tulip fields, Keukenhof — our experts compile a flawless application and guide you through VFS submission.',
    requirements:['Valid passport (min 3 months beyond return date)','Two Schengen-spec photos','Confirmed flights & accommodation','Travel insurance (€30,000 cover)','Bank statements (3 months)','Employment & leave letter'],
    includes:['VFS appointment booking','Document compilation','Application form filling','Expert document review','Embassy coordination'],
  },
  {
    c:'Greece', slug:'greece', urlSlug:'greece', f:'🇬🇷', type:'sticker', region:'europe',
    val:'90 days', docs:'7 docs', proc:'15 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&q=90&fit=crop&auto=format',
    fullName:'Greece (Schengen)', capital:'Athens', currency:'EUR (Euro)', language:'Greek',
    successRate:'94%',
    about:'Greece Schengen visa lets you island-hop between Santorini, Mykonos, and Crete while covering all of Europe. Our team ensures a thorough, rejection-proof application.',
    requirements:['Valid passport (min 3 months beyond return date)','Two Schengen-spec photos','Confirmed flights & island accommodation','Travel insurance (€30,000 cover)','Bank statements (3 months)','Salary slips & ITR'],
    includes:['VFS appointment booking','Document compilation & review','Application form filling','Island itinerary creation','WhatsApp updates'],
  },
  {
    c:'Switzerland', slug:'switzerland', urlSlug:'switzerland', f:'🇨🇭', type:'sticker', region:'europe',
    val:'90 days', docs:'8 docs', proc:'15 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=90&fit=crop&auto=format',
    fullName:'Switzerland (Schengen)', capital:'Bern', currency:'CHF (Franc)', language:'German/French',
    successRate:'92%',
    about:'Switzerland Schengen visa for the Alps, Geneva, and Zurich. Swiss consulate requires meticulous documentation — our experts know exactly what they want.',
    requirements:['Valid passport (min 3 months beyond return date)','Two Schengen-spec photos','Flight & hotel confirmations','Travel insurance (€30,000 cover)','Bank statements (last 6 months)','ITR, salary slips, employment letter'],
    includes:['VFS appointment booking','Complete document preparation','Application form filling','Switzerland-specific cover letter','Post-submission tracking'],
  },
  {
    c:'Austria', slug:'austria', urlSlug:'austria', f:'🇦🇹', type:'sticker', region:'europe',
    val:'90 days', docs:'8 docs', proc:'15 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1609825488888-3a766db05542?w=1200&q=90&fit=crop&auto=format',
    fullName:'Austria (Schengen)', capital:'Vienna', currency:'EUR (Euro)', language:'German',
    successRate:'93%',
    about:'Austria Schengen visa unlocks Vienna, Salzburg, and the Alps. Our experts prepare every document to meet Austrian consulate standards and handle VFS appointment booking.',
    requirements:['Valid passport (min 3 months beyond return date)','Two Schengen-spec photos','Return flights & accommodation','Travel insurance (€30,000 minimum)','Bank statements & ITR','Employment/leave letter'],
    includes:['VFS appointment booking','Document compilation','Application form filling','Expert review','WhatsApp tracking'],
  },
  {
    c:'Portugal', slug:'portugal', urlSlug:'portugal', f:'🇵🇹', type:'sticker', region:'europe',
    val:'90 days', docs:'7 docs', proc:'15 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=90&fit=crop&auto=format',
    fullName:'Portugal (Schengen)', capital:'Lisbon', currency:'EUR (Euro)', language:'Portuguese',
    successRate:'95%',
    about:'Portugal has one of the fastest Schengen visa processing times and highest approval rates for Indians. Explore Lisbon, Porto, and the Algarve with our expert-compiled application.',
    requirements:['Valid passport (min 3 months beyond return date)','Two Schengen-spec photos','Confirmed return flights & stays','Travel insurance (€30,000 cover)','Bank statements (3 months)','Salary slips & employment letter'],
    includes:['VFS appointment booking','Document compilation','Application form filling','Expert review','WhatsApp updates'],
  },
  {
    c:'Bahrain', slug:'bahrain', urlSlug:'bahrain', f:'🇧🇭', type:'evisa', region:'middle-east',
    val:'14 days', docs:'2 docs', proc:'48 hrs', price:'₹999',
    img:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=90&fit=crop&auto=format',
    fullName:'Bahrain', capital:'Manama', currency:'BHD (Dinar)', language:'Arabic',
    successRate:'99%',
    about:'Bahrain e-Visa is one of the easiest Gulf visas for Indians — issued entirely online in 48 hours. Perfect for a weekend trip from any Indian city.',
    requirements:['Valid passport (min 6 months validity)','Passport-size digital photo (white bg)','Return air ticket or onward travel proof'],
    includes:['e-Visa application filing','Document quality check','Email delivery of visa','WhatsApp status updates'],
  },
  {
    c:'Oman', slug:'oman', urlSlug:'oman', f:'🇴🇲', type:'evisa', region:'middle-east',
    val:'30 days', docs:'2 docs', proc:'48 hrs', price:'₹999',
    img:'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=1200&q=90&fit=crop&auto=format',
    fullName:'Oman', capital:'Muscat', currency:'OMR (Rial)', language:'Arabic',
    successRate:'98%',
    about:'Oman e-Visa lets Indians explore Muscat, Wahiba Sands, and the stunning Omani coastline. Issued online and delivered to your email within 48 hours.',
    requirements:['Valid passport (min 6 months validity)','Digital passport photo (white bg)','Return air ticket'],
    includes:['e-Visa application submission','Document review','Email delivery','WhatsApp tracking'],
  },
  {
    c:'Qatar', slug:'qatar', urlSlug:'qatar', f:'🇶🇦', type:'evisa', region:'middle-east',
    val:'30 days', docs:'2 docs', proc:'24 hrs', price:'₹999',
    img:'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=1200&q=90&fit=crop&auto=format',
    fullName:'Qatar', capital:'Doha', currency:'QAR (Riyal)', language:'Arabic',
    successRate:'99%',
    about:'Qatar e-Visa is issued online within 24 hours for most Indian passport holders. Doha\'s skyline, museums, and desert experiences await — and transit passengers can get a free visa too.',
    requirements:['Valid passport (min 6 months validity)','Digital passport photo','Return air ticket','Hotel booking confirmation'],
    includes:['e-Visa application filing','Document quality check','Email delivery of visa','WhatsApp updates'],
  },
  {
    c:'Saudi Arabia', slug:'saudi-arabia', urlSlug:'saudi-arabia', f:'🇸🇦', type:'evisa', region:'middle-east',
    val:'90 days', docs:'4 docs', proc:'72 hrs', price:'₹1,499',
    img:'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=1200&q=90&fit=crop&auto=format',
    fullName:'Saudi Arabia', capital:'Riyadh', currency:'SAR (Riyal)', language:'Arabic',
    successRate:'95%',
    about:"Saudi Arabia's e-Visa opens up the Kingdom's ancient Nabataean ruins at AlUla, the Jeddah old town, and the futuristic skyline of Riyadh. Issued entirely online as part of Vision 2030 — get yours in 72 hours.",
    requirements:['Valid Indian passport (min. 6 months validity)','Recent passport-size photo (white background)','Confirmed return air ticket','Hotel booking or accommodation proof','Last 3 months bank statements','Travel insurance covering Saudi Arabia'],
    includes:['Professional e-Visa application review','e-Visa delivery to email within 72 hours','Real-time WhatsApp updates','Re-apply free if rejected (Pro plan)','GST invoice for business travel'],
  },
  {
    c:'Jordan', slug:'jordan', urlSlug:'jordan', f:'🇯🇴', type:'evisa', region:'middle-east',
    val:'30 days', docs:'3 docs', proc:'3 days', price:'₹1,299',
    img:'https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=1200&q=90&fit=crop&auto=format',
    fullName:'Jordan', capital:'Amman', currency:'JOD (Dinar)', language:'Arabic',
    successRate:'96%',
    about:"Jordan's e-Visa gives you access to Petra, the rose-red city carved into rock, the Dead Sea, and Wadi Rum desert. Simple online application — approved in 3 days, valid for 30 days of exploration.",
    requirements:['Valid Indian passport (min. 6 months validity)','Recent passport-size photo (white background)','Confirmed return air ticket','Hotel booking or accommodation proof','Travel insurance'],
    includes:['e-Visa application preparation & submission','e-Visa delivery to email','Jordan entry requirements guide','Real-time WhatsApp updates','Re-apply free if rejected (Pro plan)'],
  },
  {
    c:'Kuwait', slug:'kuwait', urlSlug:'kuwait', f:'🇰🇼', type:'sticker', region:'middle-east',
    val:'90 days', docs:'5 docs', proc:'7 days', price:'₹2,499',
    img:'https://images.unsplash.com/photo-1622396636121-db0ad48f4e6e?w=1200&q=90&fit=crop&auto=format',
    fullName:'Kuwait', capital:'Kuwait City', currency:'KWD (Dinar)', language:'Arabic',
    successRate:'93%',
    about:'Kuwait requires a visa for Indian passport holders, processed through the embassy. With one of the largest Indian communities in the Gulf, we handle hundreds of Kuwait visa applications monthly — with strong approval rates.',
    requirements:['Valid Indian passport (min. 6 months validity)','Two recent passport photos (white background)','Confirmed return air ticket','Hotel booking or sponsor invitation letter','Last 3 months bank statements'],
    includes:['Complete application package preparation','Embassy submission coordination','Real-time WhatsApp updates','Follow-up with embassy if delayed','Re-apply support if rejected (Pro plan)'],
  },
  {
    c:'Egypt', slug:'egypt', urlSlug:'egypt', f:'🇪🇬', type:'evisa', region:'africa',
    val:'30 days', docs:'2 docs', proc:'48 hrs', price:'₹1,999',
    img:'https://images.unsplash.com/photo-1539768942893-daf53e448371?w=1200&q=90&fit=crop&auto=format',
    fullName:'Egypt', capital:'Cairo', currency:'EGP (Pound)', language:'Arabic',
    successRate:'98%',
    about:'Egypt e-Visa lets Indians explore the Pyramids of Giza, the Nile, and the Red Sea. Issued online and accepted at all Egyptian international airports.',
    requirements:['Valid passport (min 6 months validity)','Digital passport photo (white bg)','Return air ticket','Hotel booking confirmation'],
    includes:['e-Visa application filing','Document review','Email delivery','Travel tips for Cairo & Luxor'],
  },
  {
    c:'Tanzania', slug:'tanzania', urlSlug:'tanzania', f:'🇹🇿', type:'evisa', region:'africa',
    val:'90 days', docs:'3 docs', proc:'3 days', price:'₹1,999',
    img:'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1200&q=90&fit=crop&auto=format',
    fullName:'Tanzania', capital:'Dodoma', currency:'TZS (Shilling)', language:'Swahili',
    successRate:'97%',
    about:'Tanzania e-Visa for the Serengeti, Kilimanjaro, and Zanzibar. Issued online through the Tanzania Immigration portal — we handle the entire process and Yellow Fever guidance.',
    requirements:['Valid passport (min 6 months validity)','Digital passport photo','Return air ticket','Yellow Fever vaccination certificate','Hotel or safari booking'],
    includes:['Tanzania immigration portal application','Vaccination guidance','Safari booking tips','WhatsApp updates','e-Visa email delivery'],
  },
  {
    c:'South Africa', slug:'south-africa', urlSlug:'south-africa', f:'🇿🇦', type:'evisa', region:'africa',
    val:'90 days', docs:'6 docs', proc:'10 days', price:'₹2,499',
    img:'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1200&q=90&fit=crop&auto=format',
    fullName:'South Africa', capital:'Cape Town / Pretoria', currency:'ZAR (Rand)', language:'English',
    successRate:'92%',
    about:"South Africa's e-Visa for Indians covers Cape Town, the Garden Route, Kruger National Park safaris, and the Winelands. Our experts navigate the document-heavy application so your safari holiday isn't delayed.",
    requirements:['Valid Indian passport (min. 30 days validity beyond return date)','Two recent passport photos (35mm × 45mm)','Confirmed return air ticket','Hotel bookings for entire stay','Last 3 months bank statements (min. ₹2 lakh balance)','Yellow fever vaccination certificate (if transiting through endemic zones)'],
    includes:['Complete document review & gap analysis','e-Visa application submission','Real-time WhatsApp updates','Rejection analysis + re-apply guidance (Pro plan)','GST invoice for business travel'],
  },
  {
    c:'Canada', slug:'canada', urlSlug:'canada', f:'🇨🇦', type:'sticker', region:'americas',
    val:'10 years', docs:'8 docs', proc:'60 days', price:'₹3,999',
    img:'https://images.unsplash.com/photo-1519832979-6fa011b87667?w=1200&q=90&fit=crop&auto=format',
    fullName:'Canada', capital:'Ottawa', currency:'CAD (Dollar)', language:'English/French',
    successRate:'72%',
    about:'Canada Visitor Visa (TRV) is one of the most sought-after visas for Indians. Our experts craft a compelling application with strong financial and personal ties documentation to boost your approval chances significantly.',
    requirements:['Valid passport (min 6 months validity)','Recent passport-size photo','IMM 5257 application form','Proof of funds (min ₹5 lakh equivalent)','Employment letter & leave approval','ITR for last 3 years','Bank statements (6 months)','Property/assets proof'],
    includes:['Complete document compilation','IMM form filling','Biometrics appointment guidance','Cover letter drafting','Financial strength review','WhatsApp application tracking'],
    contentSections:[
      { h2:'The Honest Truth About Canada Visa for Indians', body:'Canada\'s visitor visa rejection rate for Indian applicants exceeded 80% in late 2024 — the highest of any major destination. This is not because Indian applicants are dishonest. It\'s because IRCC (Canada\'s immigration department) uses a risk-scoring model that weighs country of origin heavily, and India is in the highest-risk tier due to historic overstay rates and immigration fraud. Understanding this is the first step to building an application that genuinely stands out. The approvals are happening — the difference between approved and rejected applications often comes down to how clearly you demonstrate that Canada is a destination you\'re visiting, not escaping to.' },
      { h2:'How Much Money Do You Need for Canada Visitor Visa?', body:'IRCC doesn\'t publish a fixed minimum, but based on current approvals, ₹8–15 lakh in accessible savings (not fixed deposits that can\'t be withdrawn without penalty) is a reasonable benchmark for a 2–3 week trip. What matters more than the number is the narrative the statements tell. A ₹12 lakh balance built up steadily over 12 months is significantly more convincing than ₹18 lakh with a suspicious large deposit three weeks before applying. Avoid the common mistake of "topping up" your account — IRCC officers specifically flag sudden balance spikes as potential arranged funds. Consistent saving, regular salary credits, and no large unexplained transfers is the profile that approves.' },
      { h2:'Canada Visa for Indian Parents Visiting Family — The Hardest Case', body:'If your child is a Canadian PR or citizen and you\'re applying to visit them, your application faces the highest scrutiny of any category. The painful irony: the very reason you want to visit (family) is treated by IRCC as evidence you might not leave. To overcome this, your application must prove two things simultaneously — that your emotional connection to your child is genuine, and that your life in India gives you compelling reasons to return. Strong assets: property ownership in India, other children or dependents who need you at home, ongoing business or employment, and a clear return air ticket. A well-drafted personal statement explaining your family situation — why you\'re visiting, for how long, and what you\'re returning to — is not optional for this category. It\'s essential.' },
      { h2:'What Canada Visa Rejection Letters Don\'t Tell You', body:'IRCC rejection letters are deliberately vague. "Insufficient ties to home country" or "not satisfied you will leave Canada" are the standard phrases, with no explanation of which document was lacking or what would have changed the decision. This creates a trap: applicants reapply with the same documents, add a slightly higher bank balance, and get the same rejection. What they don\'t know is that their rejection may have been triggered by something entirely different — a job title that IRCC associates with emigration risk, a pattern of short employment history, or simply an inconsistency between their stated income and their bank statements. Our review process goes through your application the way an IRCC officer does, flagging exactly what\'s likely creating the risk signal — before you file.' },
      { h2:'Canada Visitor Visa Step-by-Step: The Application Process', body:'The Canada visitor visa process is entirely online through the IRCC portal. You fill the IMM 5257 form, gather documents, pay CAD 185 (approx. ₹11,500) in application fees plus CAD 85 (approx. ₹5,300) for biometrics, submit online, attend biometrics at a VAC in India, and wait. Current processing times: 60–90 days from India, though it varies. There is no interview for most visitor visa applications — which sounds like an advantage but actually means the documents do 100% of the talking. A perfect document package isn\'t a bonus; it\'s the entire application. Our team handles the IMM form, writes your cover letter, reviews all financials for red flags, and tracks your application status via IRCC\'s portal throughout processing.' },
      { h2:'Canada Visa Processing Time from India in 2025', body:'Standard processing from India currently runs 60–100 days. IRCC publishes processing time estimates but these are averages — actual time depends on your application complexity, document completeness, and whether a background check is triggered. Biometrics must be completed before processing begins, which adds 1–2 weeks if the VAC appointment has a wait. Apply at least 3–4 months before your planned travel date. Express Entry or other immigration applications running simultaneously can complicate visitor visa applications — always disclose these, as IRCC will see them regardless.' },
      { h2:'Canada Visa Reapplication — The Right Approach After Rejection', body:'After a refusal, you can reapply immediately — there\'s no waiting period. But applying again within 30–60 days with minimal changes sends a signal that you don\'t understand why you were refused, which itself lowers your score. Take 2–3 months to genuinely strengthen what was weak. If your income documentation was thin, get a better employment letter, add a CA-certified income affidavit, or wait until your bank statements show a longer history of healthy balance. If ties were the issue, document them more specifically — property valuations, business registration, school admission letters for children. A second application should look meaningfully different from the first.' },
    ],
    faqs:[
      { q:'Why is Canada visitor visa rejection rate so high for Indians?', a:'IRCC uses a risk model that factors in country of origin, overstay statistics, and emigration intent signals. India has historically high overstay rates among visitor visa holders, which puts all Indian applicants in a high-scrutiny category regardless of individual circumstances. This doesn\'t make approval impossible — it means your application needs to work harder to establish genuine visitor intent. Applications that tell a clear, consistent story of a settled life in India with specific reasons to return consistently outperform those that just hit the document checklist.' },
      { q:'Can I apply for Canada visitor visa while my PR application is pending?', a:'Technically yes, but this is called "dual intent" and it significantly complicates your visitor visa application. IRCC must be satisfied that even though you have an immigration application pending, your intent in visiting is genuinely temporary. This requires a much stronger ties-to-India argument and a very clear explanation of your situation. Many agents advise against applying for visitor visa while PR is pending — but it has been done successfully with the right application strategy.' },
      { q:'What bank balance is required for Canada visitor visa from India?', a:'There\'s no official minimum, but based on current approvals, ₹8–15 lakh in accessible, organic savings is a reasonable target for a 2–3 week trip. Equally important is the pattern of those savings — regular credits over 12+ months significantly outperform a high balance that appeared suddenly before applying. Cover letter should also explain your funding source (salary, business income, savings) explicitly.' },
      { q:'How soon can I reapply after Canada visa rejection?', a:'Immediately — there is no mandatory waiting period. However, reapplying within 30–60 days without meaningful changes to your application is a common and expensive mistake. IRCC sees your previous application and rejection. A new application should genuinely address the weaknesses of the previous one, which often requires building new documentation over 2–3 months.' },
      { q:'Can my parents visit me in Canada if I have a PR?', a:'Yes, parents can visit — but this is one of the hardest visitor visa categories for Indians. The fact that a child is a PR creates a "pull factor" that IRCC weighs heavily. Parents need to demonstrate extremely strong ties to India: property they own, other children or dependents at home, ongoing pension or income source, and ideally a history of international travel where they returned as planned. A well-drafted personal statement is critical for this category.' },
      { q:'Does Canada visa rejection affect future applications for other countries?', a:'A Canada visa rejection must be declared on applications for countries that ask about it (Australia, UK, and others typically do ask). It does not automatically disqualify you — many people with Canada rejections get approved for other countries without issue. However, not disclosing a prior rejection when asked is considered misrepresentation and can permanently ban future applications. Always declare honestly.' },
    ],
  },
  {
    c:'Australia', slug:'australia', urlSlug:'australia', f:'🇦🇺', type:'evisa', region:'oceania',
    val:'3 months', docs:'4 docs', proc:'5 days', price:'₹2,999',
    img:'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=1200&q=90&fit=crop&auto=format',
    fullName:'Australia', capital:'Canberra', currency:'AUD (Dollar)', language:'English',
    successRate:'89%',
    about:'Australia Tourist Visa (subclass 600) for Indian passport holders. Sydney, Melbourne, the Great Barrier Reef — our experts prepare a compelling application with strong financial documentation.',
    requirements:['Valid passport (min 6 months validity)','Digital photo','Proof of funds (min ₹4 lakh)','Employment letter & leave approval','Bank statements (6 months)','Return flight booking','Travel insurance recommended'],
    includes:['ImmiAccount application filing','Document compilation & review','Financial strength assessment','WhatsApp application tracking','Post-grant travel tips'],
  },
  {
    c:'New Zealand', slug:'newzealand', urlSlug:'new-zealand', f:'🇳🇿', type:'evisa', region:'oceania',
    val:'3 months', docs:'4 docs', proc:'3 days', price:'₹1,999',
    img:'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=1200&q=90&fit=crop&auto=format',
    fullName:'New Zealand', capital:'Wellington', currency:'NZD (Dollar)', language:'English',
    successRate:'90%',
    about:'New Zealand Visitor Visa lets Indian travelers explore Queenstown, Milford Sound, and Hobbiton. Processed online via the NZeTA or standard visitor visa — we handle both.',
    requirements:['Valid passport (min 3 months beyond return date)','Digital passport photo','Proof of funds (NZD 1,000 per month)','Return air ticket','Employment letter & leave approval','Bank statements (3 months)'],
    includes:['NZeTA or visitor visa filing','Document quality review','Financial assessment','WhatsApp tracking','NZ travel tips'],
  },
]

export const TYPE_LABEL = { evisa:'e-Visa', voa:'Visa on Arrival', sticker:'Sticker Visa', free:'Visa Free' }
export const TYPE_CLS   = { evisa:'be', voa:'bv', sticker:'bs', free:'bf' }
export const POPULAR_SLUGS = ['uae','thailand','singapore','malaysia','indonesia','usa','uk','turkey','maldives']

export const STEPS = [
  { icon:'🔍', title:'Search & Select', desc:'Search your destination, compare visa types, check requirements and fees — all in one place.' },
  { icon:'📋', title:'Upload Documents', desc:'Fill a simple form and upload your passport & photos. Our AI checks for errors before submission.' },
  { icon:'⚡', title:'We Handle It', desc:'Our experts submit your application and track it 24/7. Get real-time WhatsApp updates at every step.' },
  { icon:'✅', title:'Receive & Travel', desc:'Your e-Visa lands in your email. Show it at the airport and explore the world. Safe travels!' },
]

export const FEATURES = [
  { cls:'b1', icon:'🛡️', iconBg:'rgba(37,99,235,0.1)', title:'On-Time Guarantee', desc:'We guarantee visa delivery before your travel date or we refund your full service fee — no questions asked.', extra:'visual' },
  { cls:'b2', icon:'🤖', iconBg:'rgba(124,58,237,0.1)', title:'AI Document Checker', desc:'Our AI scans your documents before submission to catch errors that cause delays or rejections.' },
  { cls:'b3', icon:'📱', iconBg:'rgba(22,163,74,0.1)',  title:'Live Tracking', desc:'Real-time WhatsApp & SMS updates at every stage of your application.' },
  { cls:'b4', icon:'💳', iconBg:'rgba(217,119,6,0.1)',  title:'Pay in INR', desc:'No forex markup. Pay via UPI, Net Banking, or any Indian debit/credit card.' },
  { cls:'b5', icon:'🧑‍💼', iconBg:'rgba(220,38,38,0.1)', title:'Expert Support', desc:'Hindi & English support via phone, WhatsApp, and chat. Available 7 days a week.' },
  { cls:'b6', icon:'👨‍👩‍👧‍👦', iconBg:'rgba(13,148,136,0.1)', title:'Group Applications', desc:'Apply for your entire family or travel group at once. Bulk discounts for 4+ travelers.' },
]

export const TRUST = [
  { num:'2L+', label:'Happy Travelers' }, { num:'120+', label:'Destinations' },
  { num:'98%', label:'Success Rate' }, { num:'4.8★', label:'Google Rating' },
  { num:'24/7', label:'Expert Support' }, { num:'₹0', label:'Hidden Fees' },
]

export const TESTIMONIALS = [
  { name:'Priya Sharma', city:'Mumbai', dest:'Dubai Visa', flag:'🇦🇪', color:'#2563eb', text:'Got my UAE visa in just 18 hours! The WhatsApp updates were super helpful. Will use eVisas.in for every trip.' },
  { name:'Rahul Gupta', city:'Delhi', dest:'Thailand Visa', flag:'🇹🇭', color:'#16a34a', text:'Applied for family of 4. The group application was so smooth. All 4 visas approved in 2 days. Highly recommend!' },
  { name:'Ananya Nair', city:'Bangalore', dest:'Singapore Visa', flag:'🇸🇬', color:'#7c3aed', text:'The AI document checker caught an error in my photo before I submitted. Saved me from a rejection. Very smart!' },
  { name:'Vikram Mehta', city:'Pune', dest:'Schengen Visa', flag:'🇪🇺', color:'#d97706', text:'Schengen is complicated but the team guided me every step. Got approved for 90 days. Outstanding support!' },
  { name:'Sunita Patel', city:'Ahmedabad', dest:'US Visa', flag:'🇺🇸', color:'#dc2626', text:'The mock interview tool is absolute gold. Got my B1/B2 approved on the first attempt. Incredible service!' },
  { name:'Arjun Reddy', city:'Hyderabad', dest:'UK Visa', flag:'🇬🇧', color:'#0d9488', text:'INR payment saved me forex charges. Quick, transparent and professional. Will use again for Europe trip.' },
]

export const PLANS = [
  {
    tag:'Visa Secure', amount:'499', per:'/ visa',
    desc:'Start your visa application with expert support. We handle the paperwork end to end.',
    feats:['Single visa application','Priority WhatsApp updates','Dedicated visa expert'],
    missing:['Hotel booking confirmation','Dummy airline ticket (for visa application)','Travel insurance'],
    cta:'Get Started', ctaCls:'plan-cta-ghost', featured:false
  },
  {
    tag:'Dummy Tickets Plan', amount:'1,999', per:'/ visa',
    desc:'Everything in Basic + dummy airline ticket, hotel booking & travel insurance included.',
    feats:['Single visa application','Priority WhatsApp updates','Dedicated visa expert','Hotel booking confirmation','Dummy airline ticket (for visa application)','Travel insurance'],
    missing:[],
    cta:'Apply Now →', ctaCls:'plan-cta-primary', featured:true
  },
]

export const BLOGS = [
  {
    emoji:'🇦🇪', tag:'Middle East', img:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=90&fit=crop&auto=format',
    title:'Dubai Visa for Indians: Complete 2025 Guide',
    excerpt:'Everything you need — fees, documents, processing time, and tips to avoid the most common rejection reasons.',
    date:'Apr 28, 2025', read:'5 min', author:'Priya R.', ac:'#2563eb',
    content:[
      { type:'stats', items:[{ num:'24hrs', label:'Processing Time' },{ num:'₹4,499', label:'eVisas.in Fee' },{ num:'99%', label:'Approval Rate' }] },
      { type:'section', h:'Why Dubai Remains India\'s #1 Visa Destination', p:'Dubai consistently tops the list for Indian travelers — over 40 lakh Indians visit every year. The UAE e-Visa is simple, fully online, and issued within 24 hours. Whether you\'re going for the Burj Khalifa, a business meeting, or a family vacation, the visa process is straightforward when you have the right documents.' },
      { type:'tip', title:'Processing Time Tip', text:'Apply at least 72 hours before travel — though most get approved in under 24 hours, buffer time is always wise.' },
      { type:'section', h:'Documents You\'ll Need', p:'The UAE e-Visa requires only 3 core documents for most applicants:' },
      { type:'checklist', items:['Valid Indian passport with at least 6 months validity','Recent passport-size photo (white background, 70% face coverage)','Confirmed return air ticket (booking reference is sufficient)','Hotel booking or host invitation letter','Last 3 months bank statement (min. ₹1 lakh average balance)','Travel insurance covering UAE (recommended but not always required)'] },
      { type:'section', h:'Common Rejection Reasons to Avoid', p:'Most UAE e-Visa rejections happen due to avoidable errors. The top reasons are: photo on a non-white background, bank balance below threshold, or mismatched name spelling between the passport and the booking. Our AI document checker catches all of these before submission.' },
      { type:'quote', text:'"Got my Dubai visa in 18 hours flat. The WhatsApp updates were incredibly reassuring. Applied on Monday evening, visa in my inbox by Tuesday morning." — Priya Sharma, Mumbai' },
      { type:'tip', title:'Pro Tip', text:'If you\'re a frequent Dubai traveler, consider applying for a 90-day multi-entry visa. At ₹7,999 through eVisas.in, it works out much cheaper per trip than applying each time.' },
    ]
  },
  {
    emoji:'🇸🇬', tag:'Asia', img:'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200&q=90&fit=crop&auto=format',
    title:'Singapore vs Thailand: Which Visa is Easier for Indians?',
    excerpt:'Comparing costs, processing time, and approval rates for two of India\'s most popular holiday destinations.',
    date:'Apr 22, 2025', read:'7 min', author:'Rahul M.', ac:'#16a34a',
    content:[
      { type:'stats', items:[{ num:'97%', label:'Singapore Approval' },{ num:'98%', label:'Thailand Approval' },{ num:'3 days', label:'Singapore Processing' }] },
      { type:'section', h:'The Big Question: Singapore or Thailand First?', p:'Both Singapore and Thailand are among the easiest Asian visas for Indians — but they work very differently. Singapore issues a proper e-Visa (EPAS) online in 3 business days. Thailand offers a Visa on Arrival at the airport. The right choice depends on your travel style and how much advance planning you do.' },
      { type:'section', h:'Singapore: The Online Advantage', p:'Singapore\'s e-Visa (called EPAS) is applied online and linked electronically to your passport. No sticker, no stamp needed until you arrive. Processing takes 3 business days, the fee is modest, and approval rates are among the highest in Asia for Indians. The downside: you must apply in advance — you can\'t get it at the border.' },
      { type:'tip', title:'Singapore Tip', text:'If you have a valid US, UK, Australian, or Canadian visa, Singapore allows visa-free entry. Check your eligibility before applying — you might not need a visa at all!' },
      { type:'section', h:'Thailand: The Visa on Arrival Option', p:'Thailand\'s Visa on Arrival (VOA) is available at Bangkok Suvarnabhumi, Phuket, and Chiang Mai airports. Cost is 2,000 THB (≈₹4,800) paid in cash at the counter. The catch: VOA queues can be very long — sometimes 2+ hours — and you need cash in Thai Baht. We recommend applying for an e-Visa before travel to skip the queue entirely.' },
      { type:'checklist', items:['Singapore: Apply 5–7 days before travel online','Thailand: Apply for e-Visa 2 weeks before OR get VOA at airport','Singapore fee: ₹3,499 (eVisas.in) + SGD 30 govt fee','Thailand VOA: 2,000 THB cash at airport','Both require: passport 6 months valid, return ticket, hotel booking'] },
      { type:'quote', text:'"Applied for both Singapore and Thailand in one go through eVisas.in. Got the Singapore approval in 2 days and the Thailand e-Visa in 3. Zero airport queues." — Rahul Gupta, Delhi' },
      { type:'section', h:'Our Recommendation', p:'For first-time Southeast Asia travelers: start with Singapore (easier immigration, English-speaking, safe). For beach lovers who want to be spontaneous: Thailand VOA works, but book the e-Visa version for a smoother experience. Either way, eVisas.in handles both seamlessly.' },
    ]
  },
  {
    emoji:'🇪🇺', tag:'Europe', img:'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&q=90&fit=crop&auto=format',
    title:'Schengen Visa Rejected? Here\'s Why & How to Fix It',
    excerpt:'The most common reasons Indians get rejected — and exactly how to fix each one before reapplying.',
    date:'Apr 15, 2025', read:'9 min', author:'Ananya K.', ac:'#7c3aed',
    content:[
      { type:'stats', items:[{ num:'32%', label:'India Rejection Rate' },{ num:'68%', label:'Strong App Approval' },{ num:'15 days', label:'Avg Processing' }] },
      { type:'section', h:'Why Schengen Rejections Are More Common Than You Think', p:'India has one of the highest Schengen visa rejection rates globally — roughly 28–32% of applications are refused. But the good news: the vast majority of rejections are due to fixable documentation errors, not genuine immigration concerns. Understanding why you were refused is the first step to a successful reapplication.' },
      { type:'section', h:'The Top 7 Reasons for Schengen Rejection', p:'After analyzing 10,000+ Indian Schengen applications, these are the most common rejection reasons:' },
      { type:'checklist', items:['Insufficient bank balance (rule: min €60–100/day + return ticket cost)','Bank statement showing recent large deposits (looks suspicious — embassies want to see 3-month history)','Travel insurance below €30,000 cover or with a gap in dates','Vague or undetailed travel itinerary (must account for every day)','Employment letter missing salary details or leave approval','Mismatch between declared itinerary and booked accommodation','Weak ties to India (no property, no family, no job — suggests immigration intent)'] },
      { type:'tip', title:'The #1 Fix', text:'Get a 3-month bank statement showing a consistent balance — NOT a single large top-up before applying. Embassies flag sudden deposits as document manipulation.' },
      { type:'section', h:'How to Reapply Successfully', p:'You can reapply immediately after a Schengen rejection — there\'s no mandatory waiting period. However, you must address every refusal reason clearly in your new application. Our Pro plan includes a free reapplication with a detailed rejection analysis and a personalized action plan to fix each issue.' },
      { type:'quote', text:'"Got rejected twice before using eVisas.in. They analyzed my refusal letter, rewrote my cover letter, and helped me get the right bank statement format. Approved on my third try." — Ananya Nair, Bangalore' },
      { type:'tip', title:'Cover Letter Strategy', text:'Every strong Schengen application needs a custom cover letter that explains your travel purpose, your ties to India (job, family, property), and your ability to fund the trip. This single document can flip a rejection into an approval.' },
    ]
  },
  {
    emoji:'🇺🇸', tag:'Americas', img:'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=1200&q=90&fit=crop&auto=format',
    title:'US B1/B2 Interview: 20 Questions & Best Answers',
    excerpt:'Real questions asked at US consulates in India, with sample answers that got 10,000+ applicants approved.',
    date:'Apr 10, 2025', read:'12 min', author:'Vikram S.', ac:'#d97706',
    content:[
      { type:'stats', items:[{ num:'87%', label:'eVisas.in Success Rate' },{ num:'68%', label:'National Average' },{ num:'10yr', label:'Visa Validity' }] },
      { type:'section', h:'The US Visa Interview: What to Really Expect', p:'The US B1/B2 visa interview at Indian consulates (Mumbai, Delhi, Chennai, Kolkata, Hyderabad) is typically 2–5 minutes long. The consular officer has already reviewed your file — the interview is about confirming your intent and verifying your story. Confidence, clarity, and consistency matter more than memorized scripts.' },
      { type:'tip', title:'Golden Rule', text:'Never lie or exaggerate. Consular officers are trained to detect inconsistencies. Be honest, brief, and consistent with what\'s in your DS-160 form.' },
      { type:'section', h:'Most Asked Questions & How to Answer', p:'Here are the most common questions at Indian consulates, with the type of answer that works:' },
      { type:'checklist', items:['"What is the purpose of your visit?" → State it simply: Tourism / Business meeting / Conference. One sentence.','"Who is sponsoring your trip?" → Be clear: self-funded / company-sponsored. Have bank statements ready.','"Do you have family in the US?" → Be honest. Having family is fine — but state you\'re visiting, not immigrating.','"What do you do in India?" → Job title, company name, how long you\'ve been there. Stability matters.','"Have you traveled abroad before?" → List recent trips confidently. Strong travel history helps enormously.','"Why do you want to visit the US?" → Specific reason: Niagara, Grand Canyon, Disney, client meeting.','"When do you plan to return?" → Give your exact return date and explain why you must be back (job, family).','"What is your monthly salary?" → State it clearly. Show Form 16 or salary slips if asked.'] },
      { type:'section', h:'What the 13% Rejection Cases Have in Common', p:'Most US visa rejections under Section 214(b) come from failing to demonstrate strong ties to India. The officer must believe you will return. Weak cases: no steady job, no property, no dependents, first-time passport with no travel history. Our mock interview tool and coaching session address all of these systematically.' },
      { type:'quote', text:'"The mock interview tool asked me every single question that came up in my real interview. Got approved in under 3 minutes. The preparation was everything." — Vikram Mehta, Pune' },
    ]
  },
  {
    emoji:'✈️', tag:'Tips', img:'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1200&q=90&fit=crop&auto=format',
    title:'How to Build a Strong Travel History for Visa Approvals',
    excerpt:'Consulates scrutinise travel history. Here\'s how to build it strategically to maximise approval chances.',
    date:'Apr 5, 2025', read:'6 min', author:'Sunita P.', ac:'#dc2626',
    content:[
      { type:'stats', items:[{ num:'3×', label:'Higher Approval with History' },{ num:'5+', label:'Stamps = Strong Profile' },{ num:'0', label:'Cost for VOA Countries' }] },
      { type:'section', h:'Why Travel History Is Your Most Powerful Visa Asset', p:'Every consular officer reviews your passport stamps before deciding. A passport full of previous visas — especially from the US, UK, EU, or other strong democracies — signals you\'re a legitimate traveler with no immigration intent. A blank passport, especially for a first US or Schengen application, is a significant hurdle.' },
      { type:'section', h:'The Smart Sequence: Start Easy, Go Big', p:'The most effective strategy is to build your passport profile progressively. Start with zero-hassle destinations that leave stamps or entry records, then use that history to apply for harder visas.' },
      { type:'checklist', items:['Step 1: Visa-free destinations — Nepal, Maldives, Mauritius, Morocco (leave stamps)','Step 2: Easy e-Visas — UAE, Thailand, Singapore, Sri Lanka (leave entry records)','Step 3: Mid-tier sticker visas — Turkey, Malaysia, Indonesia','Step 4: Premium destinations — US, UK, Canada, Australia, Schengen','Step 5: Once you have US/UK/Schengen — most other visas become significantly easier'] },
      { type:'tip', title:'The Southeast Asia Trick', text:'Visit 3–4 SE Asian countries (Thailand, Vietnam, Cambodia, Singapore) in a single trip. You\'ll collect 6–8 stamps in your passport and build a strong travel profile at a very low cost.' },
      { type:'section', h:'How to Document Your Travel History Correctly', p:'Always carry your old passports if they contain stamps from previous trips. Even if your passport has expired, the stamps are valid evidence. Make high-quality photocopies of every entry/exit stamp. When applying for visas, include these as supporting documents even when not explicitly required — it demonstrates your travel pattern clearly.' },
      { type:'quote', text:'"After 4 SE Asian trips, I applied for UK and got it approved first time. Travel history was specifically mentioned as a positive factor by my visa advisor." — Sunita Patel, Ahmedabad' },
    ]
  },
  {
    emoji:'📋', tag:'Documents', img:'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=90&fit=crop&auto=format',
    title:'Visa Photo Requirements: Country-Wise Guide 2025',
    excerpt:'Wrong photo size is the #1 reason for processing delays. Use this guide to get it right the first time.',
    date:'Mar 30, 2025', read:'4 min', author:'Arjun R.', ac:'#0d9488',
    content:[
      { type:'stats', items:[{ num:'#1', label:'Photo = Top Delay Reason' },{ num:'23%', label:'Apps Delayed by Photo' },{ num:'10+', label:'Different Spec Sets' }] },
      { type:'section', h:'Why Visa Photos Cause More Problems Than You Think', p:'Passport-size photo requirements vary significantly between countries — and a single incorrect photo can delay your application by days or cause outright rejection. The three most common errors are: wrong background colour, incorrect dimensions, and face coverage outside the required range. This guide covers the major destinations.' },
      { type:'section', h:'Country-by-Country Photo Specifications', p:'' },
      { type:'checklist', items:['🇦🇪 UAE: 4×6cm (43×55mm), white background, 80% face, matte finish','🇺🇸 USA: 5×5cm (2×2 inch), white background, 50% face, no glasses','🇪🇺 Schengen: 3.5×4.5cm, white/light grey background, 70–80% face, neutral expression','🇬🇧 UK: 35×45mm, plain light grey background, no glasses since 2018','🇸🇬 Singapore: 35×45mm, white background, 70–80% face, eyes open','🇯🇵 Japan: 45×45mm, white background, face 32–36mm height, taken within 6 months','🇨🇦 Canada: 50×70mm (2×2.75 inch), white background, 31–36mm face height','🇦🇺 Australia: 35×45mm, white background, neutral expression, no glasses'] },
      { type:'tip', title:'Universal Rules That Apply Everywhere', text:'Plain background (white or light grey) · Neutral expression, mouth closed · Eyes fully open and clearly visible · No glasses (most countries now ban them) · Taken within the last 6 months · No headgear unless for religious reasons · High resolution, not pixelated or blurry' },
      { type:'section', h:'Digital Photo Requirements (for e-Visas)', p:'Online visa applications require digital photos — not scanned prints. Requirements are typically: JPEG format, minimum 600×600 pixels, maximum 5MB file size, and a white background. Our AI photo checker verifies your digital photo against the destination-specific requirements before you submit.' },
      { type:'quote', text:'"Saved 4 days of delay because the AI checker flagged my photo had a slightly grey background instead of pure white. Fixed it in 2 minutes." — Arjun Reddy, Hyderabad' },
    ]
  },
]

export const FAQS = [
  { q:'How long does it take to get a visa through eVisas.in?', a:'Processing time depends on the destination. Most e-Visas are delivered within 24–72 hours. Sticker visas and embassy appointments take longer — usually 7–30 days. We always show accurate processing times before you apply, and our Pro plan guarantees delivery before your travel date.' },
  { q:'Is my data safe with eVisas.in?', a:'Absolutely. We use bank-grade 256-bit SSL encryption for all data transmission. Your passport and personal data is stored on ISO 27001 certified servers and is never shared with third parties without your explicit consent.' },
  { q:'What if my visa gets rejected?', a:'If you\'re on our Pro plan, we offer a free re-application with an improved application at no extra service charge. On all plans, we\'ll provide a detailed rejection analysis. Our 98% success rate means rejections are rare.' },
  { q:'Can I apply for multiple family members at once?', a:'Yes! Our group application feature lets you apply for your entire family in one go. Fill one primary form and replicate details across members. We offer bulk discounts for groups of 4 or more.' },
  { q:'Which payment methods are accepted?', a:'We accept all major Indian payment methods — UPI (PhonePe, GPay, Paytm), Net Banking, Debit Cards, Credit Cards (Visa, Mastercard, RuPay, Amex), and EMI options. All amounts in INR with zero forex markup.' },
  { q:'Do I need to visit an embassy or consulate?', a:'For e-Visas — no! You apply entirely online. For countries requiring a sticker visa or biometrics (like the UK, US, Schengen), you will need a brief appointment, and we guide you through scheduling it efficiently.' },
  { q:'What is the On-Time Guarantee?', a:'We guarantee that your visa will be delivered before your stated travel date. If it isn\'t — and the delay is caused by us or embassy processing — we will refund your full service fee, no questions asked.' },
  { q:'How do I get updates on my application?', a:'Once your application is submitted, our team sends real-time updates via WhatsApp and email at every stage — document review, embassy submission, and visa approval. WhatsApp us anytime at +91 86196 66129 for a status update.' },
]

export const POLICIES = {
  refund: {
    title: 'Refund Policy',
    subtitle: 'Last updated: 1 May 2025',
    sections: [
      { h:'On-Time Guarantee Refund', body:'<div class="pol-highlight">🛡️ If we fail to deliver your visa before your travel date for any covered reason, you receive a 100% refund of your eVisas.in service fee — automatically, within 24 hours.</div><p>This guarantee applies to all applications where the delay is caused by our team or by embassy processing issues that we were aware of and failed to communicate.</p>' },
      { h:'Standard Refund Conditions', body:'<ul><li>Refund requests must be submitted within 7 days of the failed delivery date</li><li>The refund covers the eVisas.in service fee for the affected application</li><li>Refunds are processed to the original payment method within 5–7 business days</li><li>For group applications, each applicant\'s fee is refunded individually</li></ul>' },
      { h:'Non-Refundable Situations', body:'<ul><li>Applications rejected due to incorrect information provided by the applicant</li><li>Documents not submitted or submitted incorrectly by the applicant</li><li>Travel date change after submission without notifying eVisas.in</li><li>Applicant-initiated cancellations after application has been submitted to the embassy</li><li>Visa refused due to applicant\'s prior overstay, criminal record, or immigration violations</li></ul>' },
      { h:'How to Request a Refund', body:'<p>WhatsApp us at +91 86196 66129 with your booking reference and reason. Our team responds within 2 hours and processes eligible refunds within 24 hours of approval.</p>' },
    ]
  },
  privacy: {
    title: 'Privacy Policy',
    subtitle: 'Last updated: 1 May 2025',
    sections: [
      { h:'Information We Collect', body:'<p>When you apply for a visa through eVisas.in, we collect: full name, date of birth, passport number and details, contact information (email, phone), payment details (processed securely via Razorpay — we never store card numbers), and travel documents you upload.</p>' },
      { h:'How We Use Your Data', body:'<ul><li>Process your visa application with the relevant embassy or immigration authority</li><li>Send application status updates via WhatsApp, SMS, and email</li><li>Improve our services and AI document checker</li><li>Comply with legal obligations and government reporting requirements</li></ul>' },
      { h:'Data Storage & Security', body:'<div class="pol-highlight">🔒 All data is encrypted using 256-bit SSL. Servers are ISO 27001 certified. Passport scans are deleted within 90 days of visa delivery.</div><p>We use AWS infrastructure in India with regular third-party security audits. Your data is never sold, rented, or shared with marketing companies.</p>' },
      { h:'Third-Party Sharing', body:'<p>We share data only with: (1) embassies and visa processing authorities as required for your application, (2) our payment gateway (Razorpay) for transaction processing, and (3) courier services for document delivery when required. All third parties are contractually bound to data protection standards.</p>' },
      { h:'Your Rights', body:'<ul><li>Access a copy of all data we hold about you — email info@evisas.in</li><li>Request correction of incorrect personal data at any time</li><li>Request deletion of your data after your visa application is complete</li><li>Opt out of marketing communications at any time via the unsubscribe link in emails</li></ul>' },
      { h:'Contact', body:'<p>For any privacy concerns, email us at info@evisas.in or WhatsApp +91 86196 66129. We respond within 24 hours.</p>' },
    ]
  },
  terms: {
    title: 'Terms of Service',
    subtitle: 'Last updated: 1 May 2025',
    sections: [
      { h:'Acceptance of Terms', body:'<p>By using eVisas.in, you agree to these Terms of Service. If you are applying on behalf of another person, you confirm you have their consent. These terms govern all visa applications, payments, and services provided through eVisas.in.</p>' },
      { h:'Our Services', body:'<p>eVisas.in provides visa application assistance, document preparation, and submission services. We are an authorised visa facilitation service — not an embassy or government body. Final visa approval or rejection is at the sole discretion of the relevant embassy or immigration authority.</p>' },
      { h:'Applicant Responsibilities', body:'<ul><li>You must provide accurate, truthful information — any misrepresentation is your sole responsibility</li><li>Documents submitted must be genuine and valid</li><li>You must notify us immediately of any change in travel dates or personal details after application</li><li>You are responsible for meeting passport validity and other personal eligibility requirements</li></ul>' },
      { h:'Payment Terms', body:'<div class="pol-highlight">💳 All payments are in Indian Rupees (INR). Complete fees are only charged once your visa is approved.</div><p>We accept UPI, Net Banking, Debit/Credit Cards (Visa, Mastercard, RuPay, Amex), and EMI options. All transactions are secured by Razorpay.</p>' },
      { h:'Limitation of Liability', body:'<p>eVisas.in\'s liability is limited to the service fee paid for the specific application. We are not liable for losses arising from visa refusal, travel cancellations, flight or hotel costs, or any consequential damages. Our On-Time Guarantee refund (service fee only) is the maximum remedy available.</p>' },
      { h:'Governing Law', body:'<p>These terms are governed by Indian law. Any disputes shall be subject to the jurisdiction of courts in Jaipur, Rajasthan, India. For disputes under ₹50,000, we commit to resolution via online mediation within 30 days.</p>' },
    ]
  }
}
